mycalendar/calendarapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('<int:year>/<int:month>/', views.calendar_view, name='calendar'),
    path('', views.calendar_view, name='calendar'),  # Ensure this name is 'calendar'
    path('delete/<int:day_points_id>/', views.delete_day_points, name='delete_day_points'),
    #path('redeem/', views.redeem_points, name='redeem'),
    path('redeem/', views.redeem_points, name='redeem_points'),
    path('delete_redeem/<int:redeem_id>/', views.delete_redeem, name='delete_redeem'),
    path('remove-redemption/<int:redemption_id>/', views.remove_redemption, name='remove_redemption'),
    path('request-points/', views.request_points, name='request_points'),
    path('manage-point-requests/', views.manage_point_requests, name='manage_point_requests'),
    path('view-requests/', views.view_requests, name='view_requests'),

]

mycalendar/mycalendar/urls.py
from django.contrib import admin
from django.urls import path, include
from calendarapp.views import home, CustomLoginView
from calendarapp import views as calendar_views  # Import your app's views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from calendarapp.views import index  # Make sure to import the index view


urlpatterns = [
    path('', index, name='home'),

    path('admin/', admin.site.urls),
    path('calendar/', include('calendarapp.urls')),
    # path('', auth_views.LoginView.as_view(template_name='calendarapp/login.html'), name='login'),
    path('', CustomLoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/'), name='logout'),

    # path('', home, name='home'),  # Point the root URL to the home view
    path('login/', auth_views.LoginView.as_view(template_name='calendarapp/login.html'), name='login'),
    path('public-calendar/', calendar_views.public_calendar_view, name='public_calendar_home'),
    path('public-calendar/<int:year>/<int:month>/', calendar_views.public_calendar_view, name='public_calendar')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mycalendar/calendarapp/models.py
from django.db import models
from PIL import Image
from django.core.files.base import ContentFile
from io import BytesIO
from django.contrib.auth.models import User

class PointRequest(models.Model):
    kid_name = models.ForeignKey(User, on_delete=models.CASCADE)
    requested_points = models.IntegerField()
    reason = models.TextField()
    status = models.CharField(max_length=10, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending')
    rejection_reason = models.TextField(blank=True, null=True)
    date_requested = models.DateField(auto_now_add=True)

    def __str__(self):
        return f"{self.kid_name.username} - {self.requested_points} points request"

class DayPoints(models.Model):
    date = models.DateField()
    points = models.IntegerField(default=0)
    kid_name = models.CharField(max_length=100) 
    redeemed_points = models.IntegerField(default=0)

    class Meta:
        unique_together = ('date', 'kid_name')  # Ensure uniqueness for the combination of date and kid_name

    def __str__(self):
        return f"{self.kid_name}: {self.date} - {self.points} points"

class Redeem(models.Model):
    kid_name = models.CharField(max_length=100)
    item_name = models.CharField(max_length=100)
    date_redeemed = models.DateField()
    points_redeemed = models.IntegerField()
    summary = models.TextField()

    class Meta:
        permissions = (
            ("can_redeem", "Can redeem points"),
        )

    def __str__(self):
        return f"{self.kid_name} redeemed {self.points_redeemed} points on {self.date_redeemed}"

class Kid(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name
    

class RedeemableItem(models.Model):
    name = models.CharField(max_length=100)
    points_required = models.IntegerField()
    image = models.ImageField(upload_to='redeemable_items/')

    def save(self, *args, **kwargs):
        if self.image:
            # Resize the image
            img = Image.open(self.image)
            img.thumbnail((80, 100), Image.Resampling.LANCZOS)  # Updated line

            # Save the resized image to a BytesIO object
            img_io = BytesIO()
            img.save(img_io, format='JPEG', quality=85)

            # Change the image field value to the new resized image
            self.image.save(self.image.name, ContentFile(img_io.getvalue()), save=False)

        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

mycalendar/calendarapp/forms.py
from django import forms
from .models import DayPoints, Redeem, Kid, RedeemableItem, PointRequest
from datetime import date

class DayPointsForm(forms.ModelForm):
    kid_name = forms.ModelChoiceField(queryset=Kid.objects.all(), empty_label="Select Kid")

    class Meta:
        model = DayPoints
        fields = ['date', 'points', 'kid_name']  # Add 'kid_name' here
        widgets = {
            'date': forms.DateInput(attrs={'type': 'date'})
        }

class RedeemForm(forms.ModelForm):
    #kid_name = forms.ModelChoiceField(queryset=Kid.objects.all(), empty_label="Select Kid")
    redeemable_item = forms.ModelChoiceField(queryset=RedeemableItem.objects.all(), required=False)
    date_redeemed = forms.DateField(
        widget=forms.DateInput(format='%Y-%m-%d', attrs={'type': 'date'}),
        initial=date.today
    )
    class Meta:
        model = Redeem
        fields = ['kid_name', 'item_name', 'date_redeemed', 'points_redeemed', 'summary', 'redeemable_item']
        widgets = {
            'date_redeemed': forms.DateInput(attrs={'type': 'date'})
        }

    def __init__(self, *args, **kwargs):
        super(RedeemForm, self).__init__(*args, **kwargs)
        # self.fields['kid_name'].disabled = True
        # self.fields['date_redeemed'].disabled = True
        
class KidForm(forms.ModelForm):
    class Meta:
        model = Kid
        fields = ['name']

class PointRequestForm(forms.ModelForm):
    class Meta:
        model = PointRequest
        fields = ['requested_points', 'reason']

mycalendar/calendarapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import DayPoints, Redeem, Kid, RedeemableItem, PointRequest
from .forms import DayPointsForm, RedeemForm, KidForm, RedeemableItem, PointRequestForm
from datetime import date
import calendar
from django.http import HttpResponse
from datetime import timedelta
from django.db.models import Sum, F
from django.core.exceptions import ValidationError
from django.contrib import messages
from django.shortcuts import redirect
from django.contrib.auth.views import LoginView
from django.contrib.auth.decorators import login_required, user_passes_test, permission_required

def is_admin(user):
    return user.is_superuser

def home(request):
    return render(request, 'calendarapp/home.html')

class CustomLoginView(LoginView):
    template_name = 'calendarapp/login.html'

    def get_success_url(self):
        user = self.request.user
        if user.is_superuser:
            return '/calendar/'  # URL for admin
        else:
            return '/public-calendar/'  # URL for kids


@login_required
def calendar_view(request, year=date.today().year, month=date.today().month):
    if not request.user.is_superuser:
        messages.error(request, "You do not have permission to access this page.")
        return redirect('public_calendar_home')
    
    # month_days = calendar.monthrange(year, month)[1]
    first_day = date(year, month, 1)
# Calculate previous and next month
    first_day_of_current_month = date(year, month, 1)
    last_day_of_previous_month = first_day_of_current_month - timedelta(days=1)
    first_day_of_next_month = first_day_of_current_month + timedelta(days=calendar.monthrange(year, month)[1])

    if request.method == 'POST':
        form = DayPointsForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('calendar', year=year, month=month)
    else:
        form = DayPointsForm()

    points_list = list(DayPoints.objects.filter(date__year=year, date__month=month).values('id','date', 'points', 'kid_name'))
    total_points = DayPoints.objects.aggregate(Sum('points'))['points__sum'] or 0
    total_redeemed = DayPoints.objects.aggregate(Sum('redeemed_points'))['redeemed_points__sum'] or 0
    available_points = total_points - total_redeemed
    # Aggregate points and redeemed points per kid
    kids_points = DayPoints.objects.values('kid_name').annotate(
        total_points=Sum('points')
    ).order_by('kid_name')

    redeemed_points = Redeem.objects.values('kid_name').annotate(
        total_redeemed=Sum('points_redeemed')
    )

    # Convert redeemed_points to a dictionary for easier lookup
    redeemed_dict = {item['kid_name']: item['total_redeemed'] for item in redeemed_points}

    # Calculate available points
    for kid in kids_points:
        kid['total_redeemed'] = redeemed_dict.get(kid['kid_name'], 0)
        kid['available_points'] = kid['total_points'] - kid['total_redeemed']
    redeemed_points_list = Redeem.objects.filter(date_redeemed__year=year, date_redeemed__month=month).values('id', 'date_redeemed', 'item_name', 'points_redeemed', 'kid_name', 'summary')

    # Create a calendar that starts on Monday
    cal = calendar.Calendar(firstweekday=0)  # Monday is 0
    month_days = cal.monthdayscalendar(year, month)

    context = {
        'form': form,
        'year': year,
        'month': month,
        'points': {day.date.day: day.points for day in DayPoints.objects.filter(date__year=year, date__month=month)},
        'prev_month': last_day_of_previous_month.month,
        'prev_year': last_day_of_previous_month.year,
        'next_month': first_day_of_next_month.month,
        'next_year': first_day_of_next_month.year,
        'points_list': points_list,
        'total_points': total_points,
        'available_points': available_points,
        'kids_points': kids_points,
        'redeemed_points_list': redeemed_points_list,
        'is_admin': request.user.is_superuser,
        'month_days': month_days,
        }
    return render(request, 'calendarapp/calendar.html', context)

def public_calendar_view(request, year=date.today().year, month=date.today().month):
    # month_days = calendar.monthrange(year, month)[1]
    first_day = date(year, month, 1)
    # Calculate previous and next month
    first_day_of_current_month = date(year, month, 1)
    last_day_of_previous_month = first_day_of_current_month - timedelta(days=1)
    first_day_of_next_month = first_day_of_current_month + timedelta(days=calendar.monthrange(year, month)[1])

    points_list = list(DayPoints.objects.filter(date__year=year, date__month=month).values('id','date', 'points', 'kid_name'))
    total_points = DayPoints.objects.aggregate(Sum('points'))['points__sum'] or 0
    total_redeemed = DayPoints.objects.aggregate(Sum('redeemed_points'))['redeemed_points__sum'] or 0
    available_points = total_points - total_redeemed
    # Aggregate points and redeemed points per kid
    kids_points = DayPoints.objects.values('kid_name').annotate(
        total_points=Sum('points')
    ).order_by('kid_name')

    redeemed_points = Redeem.objects.values('kid_name').annotate(
        total_redeemed=Sum('points_redeemed')
    )

    # Convert redeemed_points to a dictionary for easier lookup
    redeemed_dict = {item['kid_name']: item['total_redeemed'] for item in redeemed_points}

    # Calculate available points
    for kid in kids_points:
        kid['total_redeemed'] = redeemed_dict.get(kid['kid_name'], 0)
        kid['available_points'] = kid['total_points'] - kid['total_redeemed']
    redeemed_points_list = Redeem.objects.filter(date_redeemed__year=year, date_redeemed__month=month).values('id', 'date_redeemed', 'item_name', 'points_redeemed', 'kid_name', 'summary')
    
    # No forms in context
  # Create a calendar that starts on Monday
    cal = calendar.Calendar(firstweekday=0)  # Monday is 0
    month_days = cal.monthdayscalendar(year, month)

    context = {
        'month_days': month_days,
        'year': year,
        'month': month,
        'points': {day.date.day: day.points for day in DayPoints.objects.filter(date__year=year, date__month=month)},
        'prev_month': last_day_of_previous_month.month,
        'prev_year': last_day_of_previous_month.year,
        'next_month': first_day_of_next_month.month,
        'next_year': first_day_of_next_month.year,
        'points_list': points_list,
        'total_points': total_points,
        'available_points': available_points,
        'kids_points': kids_points,
        'redeemed_points_list': redeemed_points_list,
        }
    return render(request, 'calendarapp/public_calendar.html', context)


@login_required
@user_passes_test(is_admin)
def delete_day_points(request, day_points_id):
    day_points = get_object_or_404(DayPoints, pk=day_points_id)
    if request.method == "POST":
        day_points.delete()
        return redirect('calendar')  # Redirect back to the calendar view
    return render(request, 'calendarapp/delete_confirm.html', {'day_points': day_points})

@login_required
@permission_required('calendarapp.can_redeem', raise_exception=True)
def redeem_points(request):
    today = date.today()
    redeemable_items = RedeemableItem.objects.all()

    try:
        kid = Kid.objects.get(name=request.user)
    except Kid.DoesNotExist:
        kid = None    

    total_points = DayPoints.objects.filter(kid_name=kid).aggregate(Sum('points'))['points__sum'] or 0
    redeemed_points = Redeem.objects.filter(kid_name=kid).aggregate(Sum('points_redeemed'))['points_redeemed__sum'] or 0
    available_points = total_points - redeemed_points

    initial_data = {
        'date_redeemed': date.today(),  # Default to today's date
        'kid_name': kid,  # Default to the logged-in user's username
    }

    if request.method == 'POST':
        form = RedeemForm(request.POST)
        if form.is_valid():
            redeem = form.save(commit=False)
            # Ensure points do not exceed available points
            total_points = DayPoints.objects.filter(kid_name=redeem.kid_name).aggregate(Sum('points'))['points__sum'] or 0
            redeemed_points = Redeem.objects.filter(kid_name=redeem.kid_name).aggregate(Sum('points_redeemed'))['points_redeemed__sum'] or 0
            available_points = total_points - redeemed_points

            if redeem.points_redeemed > available_points:
                raise ValidationError('Redeemed points cannot exceed available points.')
            redeem.save()
            return redirect('calendar')  # Redirect back to the calendar view
        else:
            print(form.errors)
            # If form is not valid, render the form with errors
            return render(request, 'calendarapp/redeem_form.html', {'form': form})
    else:
        form = RedeemForm(initial=initial_data)

    available_points = total_points - redeemed_points
    context = {
        'form': form,
        'today': today,
        'total_points': total_points,
        'redeemable_items': redeemable_items,
        'available_points': available_points,
    }
    return render(request, 'calendarapp/redeem_form.html', context)

@login_required
@user_passes_test(is_admin)
def delete_redeem(request, redeem_id):
    redeem_entry = get_object_or_404(Redeem, pk=redeem_id)
    if request.method == "POST":
        redeem_entry.delete()
        return redirect('calendar')  # Redirect back to the calendar or an appropriate page
    return render(request, 'calendarapp/delete_redeem_confirm.html', {'redeem_entry': redeem_entry})

@login_required
@user_passes_test(is_admin)
def remove_redemption(request, redemption_id):
    redemption = get_object_or_404(Redeem, pk=redemption_id)
    if request.method == "POST":
        redemption.delete()
        return redirect('calendar')  # Redirect back to the calendar view
    return render(request, 'calendarapp/remove_redemption_confirm.html', {'redemption': redemption})

def add_kid(request):

mycalendar/calendarapp/templates/calendarapp/base copy.html
{% load static %} <!-- Add this line at the top of your HTML file -->

<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}My Calendar App{% endblock %}</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/nprogress.css' %}" rel="stylesheet">
    <link href="{% static 'css/animate.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/custom.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/green.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap-progressbar-3.3.4.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/jqvmap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/daterangepicker.css' %}" rel="stylesheet">

    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
</head>




<body class="nav-sm">
    <div class="container body">
        <div class="main_container">

<!-- top navigation -->
<!-- top navigation -->
<div class="top_nav">
    <div class="nav_menu">

        <nav class="nav navbar-nav">
        <ul class=" navbar-right">
          <li class="nav-item dropdown open" style="padding-left: 15px;">
            <a href="javascript:;" class="user-profile dropdown-toggle" aria-haspopup="true" id="navbarDropdown" data-toggle="dropdown" aria-expanded="false">
                {% if user.is_authenticated %}
                <div class="user-info">
                <td>
                    <h2>Welcome: {{ user.username }}</h2>
                    <!-- Logout Form -->
                    <form action="{% url 'logout' %}" method="post" style="display: inline;">
                        {% csrf_token %}
                        <button type="submit">Logout</button>
                    </form>
                </td>
                </div>
                {% endif %}
            </a>
            <div class="dropdown-menu dropdown-usermenu pull-right" aria-labelledby="navbarDropdown">
              <a class="dropdown-item"  href="javascript:;"> Profile</a>
                <a class="dropdown-item"  href="javascript:;">
                  <span class="badge bg-red pull-right">50%</span>
                  <span>Settings</span>
                </a>
            <a class="dropdown-item"  href="javascript:;">Help</a>
              <a class="dropdown-item"  href="login.html"><i class="fa fa-sign-out pull-right"></i> Log Out</a>
            </div>
          </li>

         
        </ul>
      </nav>
    </div>
  </div>
<!-- /top navigation -->



        </div></div>

    {% block content %}
    {% endblock %}


<!-- JavaScript files should be included with the script tag -->
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/shBrushXml.js' %}"></script>
<script src="{% static 'js/shCore.js' %}"></script>

</body>
</html>

mycalendar/calendarapp/templates/calendarapp/delete_confirm.html
{% load static %} <!-- Add this line at the top of your HTML file -->

<!DOCTYPE html>
<html>
<head>
    <title>Delete Confirmation</title>
</head>
<body>
    <h1>Are you sure you want to delete this entry?</h1>
    <p>{{ day_points.kid_name }}: {{ day_points.date }} - {{ day_points.points }} pts</p>
    <form method="post">
        {% csrf_token %}
        <input type="submit" value="Confirm Delete">
        <a href="{% url 'calendar' %}">Cancel</a>
    </form>
</body>
</html>

mycalendar/calendarapp/templates/calendarapp/home.html
{% load static %} <!-- Add this line at the top of your HTML file -->

<!DOCTYPE html>
<html>
<head>
    <title>Home Page</title>
    <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
</head>
<body>
    <h1>Welcome to the Home Page!</h1>
    <a href="{% url 'public_calendar_home' %}">View Calendar</a>
    <a href="{% url 'redeem_points' %}">Go to Redeem</a> <!-- Link to the calendar -->
    <!-- Or use a button -->
    <!-- <form action="{% url 'calendar' %}">
        <input type="submit" value="Go to Calendar" />
    </form> -->
</body>
</html>

mycalendar/calendarapp/templates/calendarapp/redeem_form copy.html
{% extends 'calendarapp/base.html' %}
{% load static %}

{% block content %}
    <h1>Redeem Points</h1>
    <p>Your total points: {{ total_points }}</p>
    <p>Your available points: {{ available_points }}</p>
    {{ form.points_redeemed.as_p }}
    <p>
        <strong>Kid Name:</strong> {{ request.user.username }}
        <!-- <input name="kid_name" value="{{ request.user.username }}"> -->
        <!-- <input type="text" id="id_kid_name" name="kid_name" readonly> -->
    </p>
    
    <form method="post" id="redeemForm">
        {% csrf_token %}
        {{ form.as_p }}


        <p>
            <label for="id_kid_name">Kid Name:</label>
            <input type="text" name="kid_name" id="id_kid_name" value="{{ request.user.username }}" readonly>
        </p>
        <fieldset>
            <legend>{{ form.redeemable_item.label }}</legend>
            {% for item in redeemable_items %}
                <div>
                    <input type="radio" name="redeemable_item" id="item_{{ item.id }}" value="{{ item.id }}"
                           data-item-name="{{ item.name }}" data-item-points="{{ item.points_required }}"
                           onchange="checkPoints({{ total_points }}, {{ item.points_required }});"
                           >
                           <!-- <input type="radio" name="redeemable_item" id="item_{{ item.id }}" value="{{ item.id }}" onchange="checkPoints({{ total_points }}, {{ item.points_required }});"> -->
             
                    <label for="item_{{ item.id }}">
                        {{ item.name }} - {{ item.points_required }} pts
                        {% if item.image %}
                        <img src="{{ item.image.url }}" alt="{{ item.name }}" class="redeemable-item-image">
                        {% endif %}
                    </label>
                </div>
            {% endfor %}
        </fieldset>

        <p>
            <label for="id_points_redeemed">Points to Redeem:</label>
            <input type="text" id="id_points_redeemed" name="points_redeemed" readonly>
        </p>
        <!-- Date Redeemed -->
        <p>
            <label for="id_date_redeemed">Date Redeemed:</label>
            <input type="date" id="id_date_redeemed" name="date_redeemed" value="{{ today|date:'Y-m-d' }}">
        </p>
        <!-- Summary Field -->
        <p>
            <label for="id_summary">Summary:</label>
            <input type="text" id="id_summary" name="summary" readonly>
        </p>
        <!-- {{ form.as_p }} -->
        <button type="submit">Redeem</button>
    </form>

    <div id="statusBar"></div>
    <script>
        function checkPoints(totalPoints, itemPoints) {
            var statusBar = document.getElementById('statusBar');
            if(totalPoints >= itemPoints) {
                statusBar.innerHTML = 'You have sufficient points.';
                statusBar.style.color = 'green';
            } else {
                statusBar.innerHTML = 'Insufficient points.';
                statusBar.style.color = 'red';
            }
        }
    </script>
    <!-- <script>
        document.getElementById('redeemForm').addEventListener('submit', function() 
        {
            var selectedItem = document.querySelector('input[name="redeemable_item"]:checked');
            var summaryField = document.getElementById('summaryField');
            if (selectedItem) 
            {
                var itemName = selectedItem.getAttribute('data-item-name');
                var itemPoints = selectedItem.getAttribute('data-item-points');
                summaryField.value = itemName + ' redeemed by ' + '{{ request.user.username }}' + ' on ' + '{{ today|date:"Y-m-d" }}';
                this.appendChild('<input type="hidden" name="points_redeemed" value="' + itemPoints + '">');
            }

            // Create a new hidden input for points_redeemed
            var pointsInput = document.createElement('input');
            pointsInput.setAttribute('type', 'hidden');
            pointsInput.setAttribute('name', 'points_redeemed');
            pointsInput.setAttribute('value', itemPoints);

            // Append the new hidden input to the form
            this.appendChild(pointsInput);
        });
    </script> -->
    <script>
        document.querySelectorAll('input[name="redeemable_item"]').forEach(function(item) {
            item.addEventListener('change', function() {
                var itemPoints = this.getAttribute('data-item-points');
                document.getElementById('id_points_redeemed').value = itemPoints;
                document.getElementById('id_summary').value = this.getAttribute('data-item-name') + ' redeemed by ' + '{{ request.user.username }}' + ' on ' + '{{ today|date:"Y-m-d" }}';            });
        });
    </script>
{% endblock %}

mycalendar/calendarapp/templates/calendarapp/redeem_form.html
{% extends 'calendarapp/base.html' %}
{% load static %}

{% block content %}

<div class="col-md-12 col-sm-12  ">
    <div class="x_panel">
        <div class="x_title">
        <h1>Redeem Points</h1>
        <p>Your total points: {{ total_points }}</p>
        <p>Your available points: {{ available_points }}</p>
            <div class="clearfix"></div>
        </div> 
    <div class="x_content">
    {{ form.points_redeemed.as_p }}
    <p>
        <strong>Kid Name:</strong> {{ request.user.username }}
        <!-- <input name="kid_name" value="{{ request.user.username }}"> -->
        <!-- <input type="text" id="id_kid_name" name="kid_name" readonly> -->
    </p>
    
    <form method="post" id="redeemForm">
        {% csrf_token %}
        <!-- {{ form.as_p }} -->


        <p>
            <label for="id_kid_name">Kid Name:</label>
            <input type="text" name="kid_name" id="id_kid_name" value="{{ request.user.username }}" readonly>
        </p>

        <div class="table-responsive">
            <table class="table table-striped jambo_table bulk_action">
              <thead>
                <tr class="headings">
                  <th id="statusBar" class="column-title"> Please select Redeemable Item </th>
                  
                </tr>
              </thead>
              <tbody>
                <tr>
                <!-- <fieldset> -->
                    <!-- <legend>{{ form.redeemable_item.label }}</legend> -->
                    {% for item in redeemable_items %}
                        <td>
                            <input type="radio" name="redeemable_item" id="item_{{ item.id }}" value="{{ item.id }}"
                                data-item-name="{{ item.name }}" data-item-points="{{ item.points_required }}"
                                onchange="checkPoints({{ available_points }}, {{ item.points_required }});"
                                >
                                <!-- <input type="radio" name="redeemable_item" id="item_{{ item.id }}" value="{{ item.id }}" onchange="checkPoints({{ total_points }}, {{ item.points_required }});"> -->
                    
                            <label for="item_{{ item.id }}">
                                {{ item.name }} - {{ item.points_required }} pts
                                {% if item.image %}
                                <img src="{{ item.image.url }}" alt="{{ item.name }}" class="redeemable-item-image">
                                {% endif %}
                            </label>
                        </td>
                        {% if forloop.counter|divisibleby:3 and not forloop.last %}
                            </tr><tr>
                        {% endif %}
                    {% endfor %}
                    
                <!-- </fieldset> -->
                </tr>
                </tbody>
            </table>
        </div>


        <p>
            <label for="id_points_redeemed">Points to Redeem:</label>
            <input type="text" id="id_points_redeemed" name="points_redeemed" readonly>
        </p>
        <!-- Date Redeemed -->
        <p>
            <label for="id_date_redeemed">Date Redeemed:</label>
            <input type="date" id="id_date_redeemed" name="date_redeemed" value="{{ today|date:'Y-m-d' }}" readonly>
        </p>
        <p>
            <label for="id_item_name">Item Redeemed:</label>
            <input type="text" id="id_item_name" name="item_name" readonly>
        </p>        
        <!-- Summary Field -->
        <p>
            <label for="id_summary">Summary:</label>
            <input type="text" id="id_summary" name="summary" readonly>
        </p>
        <!-- {{ form.as_p }} -->
        <button type="submit">Redeem</button>
    </form>
</div>
</div>
</div>
    
    <script>
        function checkPoints(availablePoints, itemPoints) {
            var statusBar = document.getElementById('statusBar');
            if(availablePoints  >= itemPoints) {
                statusBar.innerHTML = 'You have sufficient points.';
                statusBar.style.color = 'green';
            } else {
                statusBar.innerHTML = 'Insufficient points.';
                statusBar.style.color = 'red';
            }
        }
    </script>
    <script>
        document.querySelectorAll('input[name="redeemable_item"]').forEach(function(item) {
            item.addEventListener('change', function() {
                var itemPoints = this.getAttribute('data-item-points');
                document.getElementById('id_points_redeemed').value = itemPoints;
                document.getElementById('id_item_name').value = this.getAttribute('data-item-name');
                document.getElementById('id_summary').value = this.getAttribute('data-item-name') + ' redeemed by ' + '{{ request.user.username }}' + ' on ' + '{{ today|date:"Y-m-d" }}';            });
                
        });
    </script>
{% endblock %}